.\"
.\" Copyright (c) 2022 Thomas Voss <mail@thomasvoss.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for
.\" any purpose with or without fee is hereby granted, provided that
.\" the above copyright notice and this permission notice appear in all
.\" copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
.\" WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
.\" AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
.\" DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA
.\" OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
.\" TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd November 15, 2022
.Dt DOASUTILS 7
.Os
.Sh NAME
.Nm doasutils
.Nd tools to use alongside doas
.Sh DESCRIPTION
.Nm
is a collection of utilities intended for use on a doas-based system.
They allow you to perform a variety of potentially common tasks in a safer
manner.
.Pp
The utilities are as follows:
.Pp
.Bl -tag -width Ds
.It Xr doasedit 8
Edit a text file requiring root access in your prefered editor, but without
running your editor as the root user.
.It Xr vidoas 8
Edit the doas configuration file and check it for syntax errors before
installing it.
.El
.Sh SEE ALSO
.Xr doas 1 ,
.Xr doasedit 8 ,
.Xr vidoas 8
.Pp
.Lk https://git.thomasvoss.com/doasutils "Source Repository"
.Sh HISTORY
The utilities that form this collection were forked from a port of
.Xr doas 1
by
.An Jesse Smith Aq Mt jessefrgsmith@yahoo.ca .
The original utilities can be found at
.Lk https://github.com/slicer69/doas .
.Sh AUTHOR
.An Thomas Voss Aq Mt mail@thomasvoss.com
